[package]
name = "riker-testkit"
version = "0.0.0"
authors = ["Lee Smith <leenozara@gmail.com>"]
description = "Tools to make testing Riker applications easier"
homepage = "http://riker.rs/logging"
license = "MIT"
readme = "README"

[dependencies]
chrono = "*"